version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"  # Updated to match new PORT in Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    shm_size: '256mb'