services:
  - type: web
    name: temfc-backend
    env: docker
    plan: free
    healthCheckPath: /health
    buildCommand: docker build -t temfc-backend .
    startCommand: docker run --shm-size=256m -p $PORT:5000 temfc-backend
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: GUNICORN_WORKER_TIMEOUT
        value: 120
    autoDeploy: true