services:
  - type: web
    name: temfc-backend
    plan: free
    region: us-west
    env: docker
    autoDeploy: false
    dockerImage: victortsrodrigues/temfc-backend:latest

    healthCheckPath: /health

    envVars:
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_PORT
        fromSecret: DB_PORT
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /app/src
      - key: PORT
        value: "5000"

    shmSize: 256mb
